site_name: FlexDash
theme:
  name: material
  icon: 
    logo: material/view-dashboard
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search

extra_css:
  - extra.css

nav:
  - "Quick Start":
    - quick-start/index.md
    - quick-start/docker.md
    - quick-start/examples.md
  - "Using FlexDash":
    - 'using-flexdash/index.md'
    - 'using-flexdash/core-concepts.md'
    - 'using-flexdash/grid-panel-layout.md'
    - 'using-flexdash/iframes.md'
  - "Widget dev cheat Sheet":
    - 'widget-dev-cheat-sheet/index.md'
  - "Developing Widgets":
    - 'developing-widgets/index.md'
