site_name: FlexDash
theme:
  name: material
  icon: 
    logo: material/view-dashboard
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search

extra_css:
  - extra.css
