site_name: FlexDash
theme:
  name: material
  favicon: docs.png
  logo: docs.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

extra_css:
  - extra.css

nav:
  - index.md
  - known-issues.md
  - "Quick Start":
    - quick-start/index.md
    - quick-start/docker.md
    - quick-start/examples.md
  - "Using FlexDash":
    - 'using-flexdash/index.md'
    - 'using-flexdash/core-concepts.md'
    - 'using-flexdash/grid-panel-layout.md'
    - 'using-flexdash/iframes.md'
    - 'using-flexdash/edit-mode.md'
    - 'using-flexdash/nr-subflows.md'
    - 'using-flexdash/array-widgets.md'
    - 'using-flexdash/colors.md'
  - "Widget dev cheat Sheet":
    - 'widget-dev-cheat-sheet/index.md'
  - "Developing Widgets":
    - 'developing-widgets/index.md'
  - "Internals":
    - 'internals/nr-entities.md'
